version: '3.1'

# Define the services/ containers to be run
services:
 angular: # name of the first service
  build: musiCal-frontend
 
 express: # name of the second service
  build: . # specify the directory of the Dockerfile
  ports:
  - "8888:8888" #specify ports mapping
  links:
  - database # link this service to the database service
 
 database: # name of the third service
  image: mysql # specify image to build container from
  ports:
  - "3306:3306" # specify port forwarding